mode: "test"

server:
  port: 8080

paths:
  nfs_root_test: "./nfs_backup/monitoring"
  nfs_root_prod: "/home/informaticaadmin/nfs_backup/monitoring"

services:
  yarn_rm_url: "http://localhost:8088"
  informatica_db:
    host: "localhost"
    port: 1433
    database: "INFORMATICA"
    user: "test_user"
    password: "test_pass"

database:
  sqlite_path: "data/history.db"
